name: atlas-correct-course
description: "Atlas-enhanced course correction with workflow chain impact analysis and historical lesson consultation"
author: "BMad + Atlas"

# Atlas Integration
atlas_features:
  consult_architecture: true    # Validate against patterns
  consult_workflow_chains: true # Impact analysis
  consult_lessons: true         # Past change outcomes
  memory_feeding: true          # Feed lessons learned

atlas_knowledge_fragments:
  required:
    - "04-architecture.md"      # Architectural constraints
    - "08-workflow-chains.md"   # Impact dependencies
  optional:
    - "06-lessons.md"           # Past corrections
    - "02-features.md"          # Feature context

# Critical variables from config
config_source: "{project-root}/_bmad/bmm/config.yaml"
output_folder: "{config_source}:output_folder"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
user_skill_level: "{config_source}:user_skill_level"
document_output_language: "{config_source}:document_output_language"
date: system-generated
sprint_artifacts: "{config_source}:sprint_artifacts"
sprint_status: "{sprint_artifacts}/sprint-status.yaml || {output_folder}/sprint-status.yaml"

# Atlas memory paths
atlas_memory: "{project-root}/_bmad/agents/atlas/atlas-sidecar"
atlas_index: "{atlas_memory}/atlas-index.csv"
atlas_knowledge: "{atlas_memory}/knowledge"

# Smart input file references
input_file_patterns:
  prd:
    description: "Product requirements for impact analysis"
    whole: "{output_folder}/*prd*.md"
    sharded: "{output_folder}/*prd*/*.md"
    load_strategy: "FULL_LOAD"
  epics:
    description: "All epics to analyze change impact"
    whole: "{output_folder}/*epic*.md"
    sharded: "{output_folder}/*epic*/*.md"
    load_strategy: "FULL_LOAD"
  architecture:
    description: "System architecture and decisions"
    whole: "{output_folder}/*architecture*.md"
    sharded: "{output_folder}/*architecture*/*.md"
    load_strategy: "FULL_LOAD"
  ux_design:
    description: "UX design specification (if UI impacts)"
    whole: "{output_folder}/*ux*.md"
    sharded: "{output_folder}/*ux*/*.md"
    load_strategy: "FULL_LOAD"
  tech_spec:
    description: "Technical specification"
    whole: "{output_folder}/tech-spec*.md"
    load_strategy: "FULL_LOAD"

installed_path: "{project-root}/_bmad/bmm/workflows/4-implementation/atlas-correct-course"
template: false
instructions: "{installed_path}/instructions.md"
validation: "{installed_path}/checklist.md"
checklist: "{installed_path}/checklist.md"
default_output_file: "{output_folder}/sprint-change-proposal-{date}.md"

standalone: true
