name: atlas-sprint-status
description: "Atlas-enhanced sprint status with workflow chain visualization and risk analysis"
author: "BMad + Atlas"

# Atlas Integration
atlas_features:
  consult_workflow_chains: true # Visualize dependencies
  consult_features: true        # Feature completion mapping
  risk_analysis: true           # Atlas-informed risk assessment

atlas_knowledge_fragments:
  required:
    - "02-features.md"          # Feature inventory
    - "08-workflow-chains.md"   # Dependencies
  optional:
    - "06-lessons.md"           # Past sprint lessons

# Critical variables from config
config_source: "{project-root}/_bmad/bmm/config.yaml"
output_folder: "{config_source}:output_folder"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
document_output_language: "{config_source}:document_output_language"
date: system-generated
sprint_artifacts: "{config_source}:sprint_artifacts"

# Atlas memory paths
atlas_memory: "{project-root}/_bmad/agents/atlas/atlas-sidecar"
atlas_index: "{atlas_memory}/atlas-index.csv"
atlas_knowledge: "{atlas_memory}/knowledge"

# Workflow components
installed_path: "{project-root}/_bmad/bmm/workflows/4-implementation/atlas-sprint-status"
instructions: "{installed_path}/instructions.md"

# Inputs
variables:
  sprint_status_file: "{sprint_artifacts}/sprint-status.yaml || {output_folder}/sprint-status.yaml"
  tracking_system: "file-system"

# Smart input file references
input_file_patterns:
  sprint_status:
    description: "Sprint status file generated by sprint-planning"
    whole: "{sprint_artifacts}/sprint-status.yaml || {output_folder}/sprint-status.yaml"
    load_strategy: "FULL_LOAD"

standalone: true
