# Atlas-Enhanced Retrospective Workflow
name: atlas-retrospective
description: "Epic retrospective with Atlas integration - feeds lessons learned, process improvements, and historical patterns back to Atlas memory. Validates against accumulated project knowledge."
author: "BMad"

config_source: "{project-root}/_bmad/bmm/config.yaml"
output_folder: "{config_source}:output_folder"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
user_skill_level: "{config_source}:user_skill_level"
document_output_language: "{config_source}:document_output_language"
date: system-generated
sprint_artifacts: "{config_source}:sprint_artifacts"

installed_path: "{project-root}/_bmad/bmm/workflows/4-implementation/atlas-retrospective"
template: false
instructions: "{installed_path}/instructions.md"

# Atlas Integration Configuration
atlas_enabled: true
atlas_agent: "{project-root}/_bmad/agents/atlas/atlas.agent.yaml"
atlas_memory: "{project-root}/_bmad/agents/atlas/atlas-sidecar/atlas-memory.md"
atlas_instructions: "{project-root}/_bmad/agents/atlas/atlas-sidecar/instructions.md"

# Atlas-specific features enabled for this workflow
atlas_features:
  historical_lessons_feeding: true    # Feed Section 6 with lessons learned
  process_strategy_feeding: true      # Feed Section 7 with process changes
  pattern_validation: true            # Validate against existing patterns
  memory_feeding: true                # Comprehensive memory updates
  push_alerts: true                   # Alert on pattern changes

required_inputs:
  - agent_manifest: "{project-root}/_bmad/_config/agent-manifest.csv"

# Smart input file references - handles both whole docs and sharded docs
# Priority: Whole document first, then sharded version
# Strategy: SELECTIVE LOAD - only load the completed epic and relevant retrospectives
input_file_patterns:
  epics:
    description: "The completed epic for retrospective"
    whole: "{output_folder}/*epic*.md"
    sharded_index: "{output_folder}/*epic*/index.md"
    sharded_single: "{output_folder}/*epic*/epic-{{epic_num}}.md"
    load_strategy: "SELECTIVE_LOAD"
  previous_retrospective:
    description: "Previous epic's retrospective (optional)"
    pattern: "{sprint_artifacts}/**/epic-{{prev_epic_num}}-retro-*.md"
    load_strategy: "SELECTIVE_LOAD"
  architecture:
    description: "System architecture for context"
    whole: "{output_folder}/*architecture*.md"
    sharded: "{output_folder}/*architecture*/*.md"
    load_strategy: "FULL_LOAD"
  prd:
    description: "Product requirements for context"
    whole: "{output_folder}/*prd*.md"
    sharded: "{output_folder}/*prd*/*.md"
    load_strategy: "FULL_LOAD"
  atlas_memory:
    description: "Atlas accumulated project knowledge"
    whole: "{project-root}/_bmad/agents/atlas/atlas-sidecar/atlas-memory.md"
    load_strategy: "FULL_LOAD"
  document_project:
    description: "Brownfield project documentation (optional)"
    sharded: "{output_folder}/*.md"
    load_strategy: "INDEX_GUIDED"

# Required files
sprint_status_file: "{sprint_artifacts}/sprint-status.yaml || {output_folder}/sprint-status.yaml"
story_directory: "{sprint_artifacts}"
retrospectives_folder: "{sprint_artifacts}"

standalone: true
