name: atlas-story-context
description: "Atlas-enhanced story context assembly with pattern guidance and existing code analysis"
author: "BMad + Atlas"

# Atlas Integration
atlas_features:
  consult_architecture: true    # Architectural patterns for implementation
  consult_features: true        # Feature-to-story mapping
  consult_testing: true         # Testing patterns and standards

atlas_knowledge_fragments:
  required:
    - "04-architecture.md"      # Architectural patterns
    - "05-testing.md"           # Testing standards
  optional:
    - "02-features.md"          # Feature inventory
    - "03-personas.md"          # User context

# Critical variables
config_source: "{project-root}/_bmad/bmm/config.yaml"
output_folder: "{config_source}:output_folder"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
document_output_language: "{config_source}:document_output_language"
story_path: "{config_source}:sprint_artifacts/stories"
date: system-generated
sprint_artifacts: "{config_source}:sprint_artifacts"
sprint_status: "{sprint_artifacts}/sprint-status.yaml || {output_folder}/sprint-status.yaml"

# Atlas memory paths
atlas_memory: "{project-root}/_bmad/agents/atlas/atlas-sidecar"
atlas_index: "{atlas_memory}/atlas-index.csv"
atlas_knowledge: "{atlas_memory}/knowledge"

# Workflow components
installed_path: "{project-root}/_bmad/bmm/workflows/4-implementation/atlas-story-context"
template: "{installed_path}/context-template.xml"
instructions: "{installed_path}/instructions.md"
validation: "{installed_path}/checklist.md"

# Smart input file references
input_file_patterns:
  prd:
    description: "Product requirements (optional)"
    whole: "{output_folder}/*prd*.md"
    sharded: "{output_folder}/*prd*/*.md"
    load_strategy: "FULL_LOAD"
  tech_spec:
    description: "Technical specification (Quick Flow track)"
    whole: "{output_folder}/tech-spec.md"
    load_strategy: "FULL_LOAD"
  architecture:
    description: "System architecture and decisions"
    whole: "{output_folder}/*architecture*.md"
    sharded: "{output_folder}/*architecture*/*.md"
    load_strategy: "FULL_LOAD"
  ux_design:
    description: "UX design specification (if UI)"
    whole: "{output_folder}/*ux*.md"
    sharded: "{output_folder}/*ux*/*.md"
    load_strategy: "FULL_LOAD"
  epics:
    description: "Epic containing this story"
    whole: "{output_folder}/*epic*.md"
    sharded_index: "{output_folder}/*epic*/index.md"
    sharded_single: "{output_folder}/*epic*/epic-{{epic_num}}.md"
    load_strategy: "SELECTIVE_LOAD"
  document_project:
    description: "Brownfield project documentation (optional)"
    sharded: "{output_folder}/index.md"
    load_strategy: "INDEX_GUIDED"

# Output configuration
default_output_file: "{story_path}/{{story_key}}.context.xml"

standalone: true
