name: atlas-deploy-story
description: "Atlas-enhanced deployment with deployment pattern validation and knowledge capture"
author: "BMad + Atlas"

# Atlas Integration
atlas_features:
  consult_process: true         # Deployment patterns
  consult_architecture: true    # Infrastructure patterns
  memory_feeding: true          # Capture deployment lessons

atlas_knowledge_fragments:
  required:
    - "07-process.md"           # Deployment strategy
  optional:
    - "04-architecture.md"      # Infrastructure patterns
    - "06-lessons.md"           # Past deployment issues

# Critical variables from config
config_source: "{project-root}/_bmad/bmm/config.yaml"
output_folder: "{config_source}:output_folder"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
date: system-generated
sprint_artifacts: "{config_source}:sprint_artifacts"
sprint_status: "{sprint_artifacts}/sprint-status.yaml || {output_folder}/sprint-status.yaml"

# Atlas memory paths
atlas_memory: "{project-root}/_bmad/agents/atlas/atlas-sidecar"
atlas_index: "{atlas_memory}/atlas-index.csv"
atlas_knowledge: "{atlas_memory}/knowledge"

# Branch configuration
branching:
  feature_prefix: "feature/"
  develop_branch: "develop"
  staging_branch: "staging"
  main_branch: "main"

# Deployment configuration
deployment:
  platform: "vercel"
  production_url: ""
  staging_url: ""
  preview_enabled: true

# Workflow components
installed_path: "{project-root}/_bmad/bmm/workflows/4-implementation/atlas-deploy-story"
instructions: "{installed_path}/instructions.xml"

standalone: true
